import type {
  DataMarketListing,
  DatasetVersionQualityReport,
  MarketplaceListing,
} from "./catalog-api";

export type CatalogScene =
  | "ppe"
  | "fire"
  | "traffic"
  | "defect"
  | "parcel"
  | "shelf"
  | "forest"
  | "crop"
  | "orchard"
  | "apiary"
  | "road-surface"
  | "road-safety"
  | "road-slope"
  | "road-environment"
  | "tunnel"
  | "bridge"
  | "urban-illegal"
  | "urban-sanitation"
  | "urban-construction-waste"
  | "urban-site"
  | "urban-advertising"
  | "urban-municipal"
  | "urban-water"
  | "urban-ecology"
  | "urban-fire"
  | "urban-crowd"
  | "urban-traffic"
  | "urban-greening";

export type CatalogMetric = {
  label: string;
  value: string;
};

export type PreviewBox = {
  label: string;
  confidence?: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export type CatalogPreview = {
  scene: CatalogScene;
  alt: string;
  boxes: PreviewBox[];
  image_url?: string;
  aspect_ratio?: number;
};

export type AlgorithmCatalogItem = MarketplaceListing & {
  is_mock: boolean;
  preview: CatalogPreview;
  metrics: CatalogMetric[];
  classes: string[];
  model_architecture: string;
  input_size: string;
  latency_p95: string;
  evaluation_basis: string;
  updated_label: string;
};

export type DataCatalogItem = DataMarketListing & {
  is_mock: boolean;
  preview: CatalogPreview;
  scene_category: string;
  price_label: string;
  annotation_type: string;
  image_size_summary: string;
  updated_label: string;
};

const mockProvider = {
  provider_workspace_id: "mock-sensemu-verified",
  provider_name: "SenseMu 精选",
};

const algorithmDefaults = {
  deployment_id: "mock-deployment",
  capability_spec_id: "mock-capability",
  capability_version_number: 1,
  pricing_unit: "request",
  status: "published",
  published_at: "2026-08-01T08:00:00Z",
  subscription_id: null,
  subscription_status: null,
  remaining_units: null,
};

const CORE_MOCK_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-ppe",
    deployment_id: "mock-deployment-ppe",
    capability_spec_id: "mock-capability-ppe",
    capability_slug: "ppe-compliance",
    capability_display_name: "安全穿戴检测",
    capability_problem_definition: "识别作业人员是否正确佩戴安全帽与反光衣。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["固定监控视角", "白天工地", "单人或多人作业区"],
    capability_unsupported_conditions: ["人员小于画面高度 4%", "严重逆光或夜间无补光"],
    endpoint_url: "/v1/marketplace/mock-alg-ppe/infer",
    model_name: "YOLO26s",
    model_version_number: 3,
    task_type: "object-detection",
    title: "工地安全穿戴检测",
    summary: "识别人员、安全帽与反光衣，并返回未规范穿戴的位置。",
    category: "安全生产",
    price_per_1000_cents: 1680,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "ppe",
      alt: "工地作业人员安全穿戴检测效果样例",
      boxes: [
        { label: "人员", confidence: "0.97", x: 12, y: 8, width: 52, height: 84 },
        { label: "安全帽", confidence: "0.95", x: 22, y: 6, width: 28, height: 22 },
        { label: "反光衣", confidence: "0.93", x: 12, y: 32, width: 51, height: 43 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "92.4%" },
      { label: "精确率", value: "90.8%" },
      { label: "召回率", value: "88.6%" },
    ],
    classes: ["人员", "安全帽", "未戴安全帽", "反光衣", "未穿反光衣"],
    model_architecture: "YOLO26s",
    input_size: "640 × 640",
    latency_p95: "48 ms",
    evaluation_basis: "独立测试集 1,280 张工地监控图像",
    updated_label: "2026-07-28",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-fire",
    deployment_id: "mock-deployment-fire",
    capability_spec_id: "mock-capability-fire",
    capability_slug: "smoke-fire-alert",
    capability_display_name: "烟火早期识别",
    capability_problem_definition: "发现仓储与生产区域中的烟雾和明火。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["仓库固定监控", "室内厂房", "可见光画面"],
    capability_unsupported_conditions: ["蒸汽密集区域", "强光直射镜头"],
    endpoint_url: "/v1/marketplace/mock-alg-fire/infer",
    model_name: "YOLO26m",
    model_version_number: 2,
    task_type: "object-detection",
    title: "仓储烟火早期识别",
    summary: "检测烟雾与明火，适合接入仓库监控做早期风险提示。",
    category: "安全生产",
    price_per_1000_cents: 2280,
    monthly_quota_units: 15000,
    is_mock: true,
    preview: {
      scene: "fire",
      alt: "仓库烟雾与明火检测效果样例",
      boxes: [
        { label: "烟雾", confidence: "0.91", x: 29, y: 2, width: 38, height: 58 },
        { label: "明火", confidence: "0.96", x: 35, y: 47, width: 25, height: 29 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "90.1%" },
      { label: "精确率", value: "91.7%" },
      { label: "召回率", value: "86.2%" },
    ],
    classes: ["烟雾", "明火"],
    model_architecture: "YOLO26m",
    input_size: "768 × 768",
    latency_p95: "72 ms",
    evaluation_basis: "独立测试集 860 段仓储与厂房画面",
    updated_label: "2026-07-22",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-traffic",
    deployment_id: "mock-deployment-traffic",
    capability_spec_id: "mock-capability-traffic",
    capability_slug: "road-vehicle-counting",
    capability_display_name: "道路车辆统计",
    capability_problem_definition: "检测并区分道路中的常见车辆，输出逐帧数量。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["城市路口", "高位固定相机", "白天与路灯夜景"],
    capability_unsupported_conditions: ["超密集拥堵遮挡", "鱼眼畸变未校正"],
    endpoint_url: "/v1/marketplace/mock-alg-traffic/infer",
    model_name: "RT-DETR-L",
    model_version_number: 5,
    task_type: "object-detection",
    title: "道路车辆检测与计数",
    summary: "区分小客车、货车、公交车与两轮车，返回位置和数量。",
    category: "智慧交通",
    price_per_1000_cents: 1980,
    monthly_quota_units: 30000,
    is_mock: true,
    preview: {
      scene: "traffic",
      alt: "城市路口车辆检测效果样例",
      boxes: [
        { label: "货车", confidence: "0.98", x: 36, y: 34, width: 48, height: 29 },
        { label: "小客车", confidence: "0.94", x: 18, y: 62, width: 30, height: 19 },
        { label: "小客车", confidence: "0.90", x: 72, y: 60, width: 24, height: 18 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "94.0%" },
      { label: "精确率", value: "92.1%" },
      { label: "召回率", value: "91.5%" },
    ],
    classes: ["小客车", "货车", "公交车", "摩托车", "自行车"],
    model_architecture: "RT-DETR-L",
    input_size: "960 × 544",
    latency_p95: "83 ms",
    evaluation_basis: "独立测试集 2,100 张城市道路图像",
    updated_label: "2026-07-30",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-defect",
    deployment_id: "mock-deployment-defect",
    capability_spec_id: "mock-capability-defect",
    capability_slug: "metal-surface-defect",
    capability_display_name: "金属表面缺陷分割",
    capability_problem_definition: "定位金属板材表面的划痕、凹坑与氧化区域。",
    capability_output_contract: "segments.v1",
    capability_verified_scenes: ["均匀产线光源", "金属板材近景", "单件通过"],
    capability_unsupported_conditions: ["镜面强反射", "相机焦距偏离标定范围"],
    endpoint_url: "/v1/marketplace/mock-alg-defect/infer",
    model_name: "YOLO26s-seg",
    model_version_number: 4,
    task_type: "segmentation",
    title: "金属表面缺陷分割",
    summary: "定位划痕、凹坑和氧化区域，输出缺陷轮廓与面积。",
    category: "工业质检",
    price_per_1000_cents: 2880,
    monthly_quota_units: 12000,
    is_mock: true,
    preview: {
      scene: "defect",
      alt: "金属板材划痕分割效果样例",
      boxes: [{ label: "划痕", confidence: "0.89", x: 22, y: 48, width: 62, height: 17 }],
    },
    metrics: [
      { label: "mAP50", value: "88.7%" },
      { label: "精确率", value: "91.2%" },
      { label: "召回率", value: "84.9%" },
    ],
    classes: ["划痕", "凹坑", "氧化"],
    model_architecture: "YOLO26s-seg",
    input_size: "1024 × 1024",
    latency_p95: "96 ms",
    evaluation_basis: "独立测试集 740 张产线质检图像",
    updated_label: "2026-07-19",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-parcel",
    deployment_id: "mock-deployment-parcel",
    capability_spec_id: "mock-capability-parcel",
    capability_slug: "parcel-counting",
    capability_display_name: "包裹检测与计数",
    capability_problem_definition: "检测传送带上的包裹并输出当前数量。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["俯拍传送带", "纸箱与软包", "稳定室内光照"],
    capability_unsupported_conditions: ["包裹完全重叠", "高速运动拖影"],
    endpoint_url: "/v1/marketplace/mock-alg-parcel/infer",
    model_name: "YOLO26n",
    model_version_number: 2,
    task_type: "object-detection",
    title: "快递包裹检测与计数",
    summary: "识别纸箱与软包，适合分拣线计数和漏件提示。",
    category: "仓储物流",
    price_per_1000_cents: 1380,
    monthly_quota_units: 50000,
    is_mock: true,
    preview: {
      scene: "parcel",
      alt: "物流传送带包裹检测效果样例",
      boxes: [
        { label: "纸箱", confidence: "0.96", x: 15, y: 14, width: 22, height: 18 },
        { label: "软包", confidence: "0.92", x: 34, y: 57, width: 24, height: 15 },
        { label: "纸箱", confidence: "0.98", x: 49, y: 70, width: 35, height: 25 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "95.6%" },
      { label: "精确率", value: "96.0%" },
      { label: "召回率", value: "93.8%" },
    ],
    classes: ["纸箱", "软包", "编织袋"],
    model_architecture: "YOLO26n",
    input_size: "640 × 640",
    latency_p95: "34 ms",
    evaluation_basis: "独立测试集 1,520 张分拣线图像",
    updated_label: "2026-07-26",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-shelf",
    deployment_id: "mock-deployment-shelf",
    capability_spec_id: "mock-capability-shelf",
    capability_slug: "retail-shelf-gap",
    capability_display_name: "货架缺货识别",
    capability_problem_definition: "识别零售货架中的连续空位和低库存区域。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["正面货架图像", "便利店与商超", "标准陈列区"],
    capability_unsupported_conditions: ["玻璃柜强反光", "大面积促销牌遮挡"],
    endpoint_url: "/v1/marketplace/mock-alg-shelf/infer",
    model_name: "YOLO26s",
    model_version_number: 1,
    task_type: "object-detection",
    title: "零售货架缺货识别",
    summary: "发现连续空位和低库存区域，返回货架层级与位置。",
    category: "智慧零售",
    price_per_1000_cents: 1880,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "shelf",
      alt: "零售货架缺货检测效果样例",
      boxes: [{ label: "缺货区域", confidence: "0.93", x: 24, y: 24, width: 51, height: 31 }],
    },
    metrics: [
      { label: "mAP50", value: "89.5%" },
      { label: "精确率", value: "90.4%" },
      { label: "召回率", value: "87.1%" },
    ],
    classes: ["缺货区域", "低库存区域"],
    model_architecture: "YOLO26s",
    input_size: "768 × 768",
    latency_p95: "61 ms",
    evaluation_basis: "独立测试集 980 张商超货架图像",
    updated_label: "2026-07-18",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-forest-health",
    deployment_id: "mock-deployment-forest-health",
    capability_spec_id: "mock-capability-forest-health",
    capability_slug: "forest-tree-health",
    capability_display_name: "林木健康巡检",
    capability_problem_definition: "从林区航拍或固定机位图像中发现枯死、倒伏和明显病害树木。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["林区航拍", "林道固定机位", "自然光可见光图像"],
    capability_unsupported_conditions: ["浓雾遮挡树冠", "单棵树小于画面高度 2%"],
    endpoint_url: "/v1/marketplace/mock-alg-forest-health/infer",
    model_name: "YOLO26m",
    model_version_number: 1,
    task_type: "object-detection",
    title: "林木健康巡检",
    summary: "发现枯死、倒伏与明显病害树木，适合林区巡检和复核调度。",
    category: "林业",
    price_per_1000_cents: 2480,
    monthly_quota_units: 18000,
    is_mock: true,
    preview: {
      scene: "forest",
      alt: "林区林木健康巡检效果样例",
      image_url: "/catalog-forest.jpg",
      aspect_ratio: 1600 / 1067,
      boxes: [
        { label: "疑似枯死树", confidence: "0.91", x: 4, y: 20, width: 18, height: 63 },
        { label: "倒伏树木", confidence: "0.88", x: 67, y: 54, width: 25, height: 18 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "87.9%" },
      { label: "精确率", value: "89.1%" },
      { label: "召回率", value: "84.7%" },
    ],
    classes: ["健康树木", "疑似枯死树", "倒伏树木", "病害斑块"],
    model_architecture: "YOLO26m",
    input_size: "1280 × 720",
    latency_p95: "76 ms",
    evaluation_basis: "独立测试集 1,460 张林区航拍与巡检图像",
    updated_label: "2026-08-02",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-forest-fire",
    deployment_id: "mock-deployment-forest-fire",
    capability_spec_id: "mock-capability-forest-fire",
    capability_slug: "forest-fire-smoke",
    capability_display_name: "森林烟火早期识别",
    capability_problem_definition: "在林区监控画面中发现早期烟雾和火点，减少人工巡屏范围。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["林区高点监控", "山地防火瞭望", "白天可见光视频"],
    capability_unsupported_conditions: ["厚云层与低云雾", "红外热成像之外的夜间画面"],
    endpoint_url: "/v1/marketplace/mock-alg-forest-fire/infer",
    model_name: "YOLO26s",
    model_version_number: 2,
    task_type: "object-detection",
    title: "森林烟火早期识别",
    summary: "识别林区早期烟雾和火点，输出告警位置与置信度。",
    category: "林业",
    price_per_1000_cents: 2980,
    monthly_quota_units: 12000,
    is_mock: true,
    preview: {
      scene: "forest",
      alt: "森林烟火早期识别效果样例",
      image_url: "/catalog-forest.jpg",
      aspect_ratio: 1600 / 1067,
      boxes: [{ label: "烟雾", confidence: "0.93", x: 49, y: 4, width: 38, height: 30 }],
    },
    metrics: [
      { label: "mAP50", value: "91.2%" },
      { label: "精确率", value: "92.4%" },
      { label: "召回率", value: "88.9%" },
    ],
    classes: ["烟雾", "火点", "高亮反光"],
    model_architecture: "YOLO26s",
    input_size: "1280 × 720",
    latency_p95: "54 ms",
    evaluation_basis: "独立测试集 920 段林区监控视频帧",
    updated_label: "2026-08-01",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-produce-sort",
    deployment_id: "mock-deployment-produce-sort",
    capability_spec_id: "mock-capability-produce-sort",
    capability_slug: "produce-sorting",
    capability_display_name: "农产品分选识别",
    capability_problem_definition: "识别常见蔬果品类和明显外观缺陷，辅助收购与分选台抽检。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["收购分选台", "农产品近景", "室内均匀光照"],
    capability_unsupported_conditions: ["目标堆叠超过 60%", "透明塑料袋强反光"],
    endpoint_url: "/v1/marketplace/mock-alg-produce-sort/infer",
    model_name: "YOLO26s",
    model_version_number: 3,
    task_type: "object-detection",
    title: "农产品分选识别",
    summary: "识别常见蔬果品类和明显外观缺陷，适合收购、分选与质检抽查。",
    category: "农业",
    price_per_1000_cents: 1680,
    monthly_quota_units: 24000,
    is_mock: true,
    preview: {
      scene: "crop",
      alt: "农产品分选识别效果样例",
      image_url: "/catalog-crop.jpg",
      aspect_ratio: 1600 / 1067,
      boxes: [
        { label: "苦瓜", confidence: "0.96", x: 8, y: 14, width: 41, height: 37 },
        { label: "黄瓜", confidence: "0.94", x: 56, y: 8, width: 37, height: 43 },
        { label: "胡萝卜", confidence: "0.92", x: 45, y: 48, width: 31, height: 39 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "94.6%" },
      { label: "精确率", value: "93.8%" },
      { label: "召回率", value: "91.7%" },
    ],
    classes: ["苦瓜", "黄瓜", "胡萝卜", "辣椒", "疑似外观缺陷"],
    model_architecture: "YOLO26s",
    input_size: "512 × 512",
    latency_p95: "41 ms",
    evaluation_basis: "独立测试集 3,200 张农产品分选图像",
    updated_label: "2026-07-31",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-orchard-count",
    deployment_id: "mock-deployment-orchard-count",
    capability_spec_id: "mock-capability-orchard-count",
    capability_slug: "orchard-fruit-counting",
    capability_display_name: "果园果实计数",
    capability_problem_definition: "检测果树上的果实并按区域统计数量，辅助产量预估。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["果园行间", "自然光树冠", "单果与小簇果实"],
    capability_unsupported_conditions: ["果实完全被叶片遮挡", "强风造成连续运动模糊"],
    endpoint_url: "/v1/marketplace/mock-alg-orchard-count/infer",
    model_name: "YOLO26n",
    model_version_number: 2,
    task_type: "object-detection",
    title: "果园果实计数",
    summary: "检测果实位置并按树行统计，适合采收前产量预估。",
    category: "农业",
    price_per_1000_cents: 2180,
    monthly_quota_units: 20000,
    is_mock: true,
    preview: {
      scene: "orchard",
      alt: "果园果实计数效果样例",
      image_url: "/catalog-orchard.jpg",
      aspect_ratio: 1600 / 1065,
      boxes: [
        { label: "果实", confidence: "0.94", x: 43, y: 20, width: 12, height: 17 },
        { label: "果实", confidence: "0.91", x: 58, y: 34, width: 14, height: 18 },
        { label: "果实", confidence: "0.89", x: 22, y: 44, width: 13, height: 17 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "90.8%" },
      { label: "精确率", value: "92.0%" },
      { label: "召回率", value: "87.6%" },
    ],
    classes: ["果实", "未成熟果", "病果"],
    model_architecture: "YOLO26n",
    input_size: "960 × 544",
    latency_p95: "39 ms",
    evaluation_basis: "独立测试集 2,480 张果园图像",
    updated_label: "2026-07-29",
  },
  {
    ...mockProvider,
    ...algorithmDefaults,
    id: "mock-alg-apiary",
    deployment_id: "mock-deployment-apiary",
    capability_spec_id: "mock-capability-apiary",
    capability_slug: "apiary-inspection",
    capability_display_name: "蜂箱巡检与计数",
    capability_problem_definition: "识别养蜂场蜂箱与巡检人员，辅助蜂场资产盘点和作业记录。",
    capability_output_contract: "detections.v1",
    capability_verified_scenes: ["蜂场固定机位", "蜂箱近景", "白天自然光视频"],
    capability_unsupported_conditions: ["蜂箱被植被大面积遮挡", "夜间无补光"],
    endpoint_url: "/v1/marketplace/mock-alg-apiary/infer",
    model_name: "YOLO26s",
    model_version_number: 1,
    task_type: "object-detection",
    title: "蜂箱巡检与计数",
    summary: "识别蜂箱和巡检人员，支持蜂场资产盘点与作业记录。",
    category: "农业",
    price_per_1000_cents: 1880,
    monthly_quota_units: 16000,
    is_mock: true,
    preview: {
      scene: "apiary",
      alt: "蜂箱巡检与计数效果样例",
      image_url: "/catalog-apiary.jpg",
      aspect_ratio: 1600 / 1063,
      boxes: [
        { label: "巡检人员", confidence: "0.97", x: 16, y: 10, width: 38, height: 77 },
        { label: "蜂箱", confidence: "0.94", x: 54, y: 23, width: 31, height: 49 },
      ],
    },
    metrics: [
      { label: "mAP50", value: "93.1%" },
      { label: "精确率", value: "94.0%" },
      { label: "召回率", value: "90.2%" },
    ],
    classes: ["蜂箱", "巡检人员", "疑似空箱"],
    model_architecture: "YOLO26s",
    input_size: "1280 × 720",
    latency_p95: "52 ms",
    evaluation_basis: "独立测试集 1,760 张蜂场巡检图像",
    updated_label: "2026-07-27",
  },
];

type MockAlgorithmInput = {
  id: string;
  title: string;
  summary: string;
  slug: string;
  problem: string;
  category: string;
  scene: CatalogScene;
  classes: string[];
  verifiedScenes: string[];
  unsupported: string[];
  boxes: PreviewBox[];
  price: number;
  quota: number;
};

function createMockAlgorithm(input: MockAlgorithmInput): AlgorithmCatalogItem {
  return {
    ...mockProvider,
    ...algorithmDefaults,
    id: input.id,
    deployment_id: `mock-deployment-${input.slug}`,
    capability_spec_id: `mock-capability-${input.slug}`,
    capability_slug: input.slug,
    capability_display_name: input.title,
    capability_problem_definition: input.problem,
    capability_output_contract: "detections.v1",
    capability_verified_scenes: input.verifiedScenes,
    capability_unsupported_conditions: input.unsupported,
    endpoint_url: `/v1/marketplace/${input.id}/infer`,
    model_name: "YOLO26m",
    model_version_number: 1,
    task_type: "object-detection",
    title: input.title,
    summary: input.summary,
    category: input.category,
    price_per_1000_cents: input.price,
    monthly_quota_units: input.quota,
    is_mock: true,
    preview: { scene: input.scene, alt: `${input.title}效果样例`, boxes: input.boxes },
    metrics: [
      { label: "mAP50", value: "待真实训练" },
      { label: "精确率", value: "待真实训练" },
      { label: "召回率", value: "待真实训练" },
    ],
    classes: input.classes,
    model_architecture: "YOLO26m",
    input_size: "1280 × 720",
    latency_p95: "待真实服务",
    evaluation_basis: "演示能力卡，待接入真实训练与独立验收",
    updated_label: "2026-09-06",
  };
}

const ROAD_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  createMockAlgorithm({ id: "mock-alg-road-surface", title: "路面病害识别", summary: "识别裂缝、坑槽、车辙、沉陷等路面病害，辅助道路巡检。", slug: "road-surface-defects", problem: "从道路巡检图像中发现并分类典型路面病害。", category: "道路工程", scene: "road-surface", classes: ["横向裂缝", "纵向裂缝", "网状裂缝", "坑槽", "车辙", "沉陷", "龟裂", "修补不良"], verifiedScenes: ["车载道路巡检", "沥青与水泥路面", "白天可见光图像"], unsupported: ["夜间无补光", "积雪与严重积水"], boxes: [{ label: "横向裂缝", confidence: "演示", x: 8, y: 40, width: 38, height: 9 }, { label: "坑槽", confidence: "演示", x: 60, y: 52, width: 22, height: 18 }], price: 2480, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-road-safety", title: "交安设施异常识别", summary: "发现护栏、防眩板、标志标牌、标线和防撞桶异常。", slug: "road-safety-facilities", problem: "从道路巡检图像中识别交通安全设施缺失、损坏和外观异常。", category: "道路工程", scene: "road-safety", classes: ["护栏缺失", "护栏损坏", "护栏污损", "护栏变形", "防眩板损坏", "防眩板缺失", "标牌反光异常", "标牌倾斜", "标牌污损", "标线不清晰", "轮廓标", "防撞桶"], verifiedScenes: ["高速公路巡检", "国省道路侧", "白天与路灯夜景"], unsupported: ["强逆光", "设施内部结构损伤"], boxes: [{ label: "护栏变形", confidence: "演示", x: 8, y: 47, width: 48, height: 18 }, { label: "标牌倾斜", confidence: "演示", x: 67, y: 12, width: 18, height: 28 }], price: 2280, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-road-slope", title: "路基边坡异常识别", summary: "识别滑坡、塌方、冲沟、防护网和挡墙异常。", slug: "road-slope-anomalies", problem: "从山区道路巡检图像中发现边坡和排水设施异常线索。", category: "道路工程", scene: "road-slope", classes: ["滑坡", "塌方", "冲沟", "防护网破损", "挡墙开裂", "挡墙倾斜", "排水沟堵塞"], verifiedScenes: ["山区公路", "雨后边坡", "车载与航拍图像"], unsupported: ["植被完全遮挡", "地质结构内部风险"], boxes: [{ label: "滑坡", confidence: "演示", x: 42, y: 11, width: 42, height: 34 }, { label: "防护网破损", confidence: "演示", x: 12, y: 38, width: 26, height: 27 }], price: 2380, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-road-environment", title: "路域环境异常识别", summary: "发现抛洒物、违法占用、绿化遮挡、积水和结冰等路况异常。", slug: "road-environment-anomalies", problem: "从道路巡检图像中发现影响通行和环境的异常目标。", category: "道路工程", scene: "road-environment", classes: ["散落物", "油污", "大件垃圾", "违章堆放", "占道施工", "枝叶侵入", "标志遮挡", "火灾烟雾", "积水", "结冰"], verifiedScenes: ["城市道路", "高速路段", "日常巡检视频"], unsupported: ["严重雨雪", "无法确认的污染成分"], boxes: [{ label: "散落物", confidence: "演示", x: 28, y: 61, width: 17, height: 12 }, { label: "占道施工", confidence: "演示", x: 57, y: 43, width: 31, height: 27 }], price: 2180, quota: 22000 }),
  createMockAlgorithm({ id: "mock-alg-tunnel", title: "隧道设施异常识别", summary: "识别洞口、衬砌、排水和照明风机等隧道设施异常。", slug: "tunnel-facility-anomalies", problem: "从隧道巡检图像中发现设施外观和结构表面异常线索。", category: "道路工程", scene: "tunnel", classes: ["洞口滑坡", "洞口落石", "防护网破损", "衬砌裂缝", "衬砌渗漏水", "衬砌剥落", "背后空洞迹象", "排水沟堵塞", "排水沟积水", "排水沟破损", "照明外观异常", "风机外观异常"], verifiedScenes: ["公路隧道", "洞口与拱顶", "车载巡检图像"], unsupported: ["不可见内部空洞", "无照明极暗画面"], boxes: [{ label: "衬砌裂缝", confidence: "演示", x: 38, y: 21, width: 25, height: 12 }, { label: "渗漏水", confidence: "演示", x: 67, y: 39, width: 15, height: 26 }], price: 2580, quota: 15000 }),
  createMockAlgorithm({ id: "mock-alg-bridge", title: "桥梁设施病害识别", summary: "识别桥面、伸缩缝、支座、墩台和梁体病害。", slug: "bridge-facility-defects", problem: "从桥梁巡检图像中发现构件表面病害和异常线索。", category: "道路工程", scene: "bridge", classes: ["桥面裂缝", "桥面坑槽", "桥面车辙", "伸缩缝堵塞", "伸缩缝损坏", "伸缩缝错位", "支座老化", "支座开裂", "支座脱空", "支座偏位", "墩台冲刷", "混凝土剥落", "钢筋锈蚀", "梁体裂缝", "梁体渗水", "梁体白华"], verifiedScenes: ["公路桥梁", "桥面与墩台", "无人机与近距离图像"], unsupported: ["构件内部损伤", "无法接近的遮挡区域"], boxes: [{ label: "桥面裂缝", confidence: "演示", x: 12, y: 47, width: 37, height: 10 }, { label: "伸缩缝堵塞", confidence: "演示", x: 55, y: 51, width: 24, height: 14 }], price: 2680, quota: 14000 }),
];

const URBAN_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  createMockAlgorithm({ id: "mock-alg-urban-illegal", title: "违法建设识别", summary: "发现楼顶搭建、露台封闭、阳光房和彩钢房等疑似违建线索。", slug: "urban-illegal-construction", problem: "从航拍与街景图像中发现建筑外观变化和疑似违建线索。", category: "城市治理", scene: "urban-illegal", classes: ["楼顶新增搭建", "露台封闭", "阳光房", "彩钢房", "新建建筑", "外立面明显变化", "疑似违建脚手架", "疑似违建围挡"], verifiedScenes: ["城市航拍", "城乡结合部", "建筑外立面"], unsupported: ["缺少历史对照影像", "无法替代规划执法认定"], boxes: [{ label: "楼顶新增搭建", confidence: "演示", x: 48, y: 12, width: 28, height: 24 }, { label: "彩钢房", confidence: "演示", x: 14, y: 51, width: 27, height: 24 }], price: 2480, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-sanitation", title: "市容环境问题识别", summary: "识别占道经营、垃圾堆积、乱贴乱画和非机动车乱停放。", slug: "urban-sanitation-issues", problem: "从网格巡查图像中发现影响市容环境的异常目标。", category: "城市治理", scene: "urban-sanitation", classes: ["占道摊位", "占道棚亭", "游商小贩", "垃圾堆积", "垃圾爆桶", "乱贴乱画", "违规广告", "非机动车乱停放", "店外经营", "店外乱堆放"], verifiedScenes: ["城市街区", "商圈与社区", "网格巡查图像"], unsupported: ["夜间低照度", "不输出商户身份和处罚结论"], boxes: [{ label: "占道摊位", confidence: "演示", x: 8, y: 48, width: 28, height: 28 }, { label: "垃圾爆桶", confidence: "演示", x: 65, y: 58, width: 18, height: 25 }], price: 2280, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-construction-waste", title: "建筑垃圾与渣土识别", summary: "发现偷倒乱倒、渣土车抛洒滴漏和露天堆放等问题。", slug: "urban-construction-waste", problem: "从道路和工地周边图像中识别建筑垃圾与渣土异常。", category: "城市治理", scene: "urban-construction-waste", classes: ["建筑垃圾偷倒", "建筑垃圾乱倒", "渣土车抛洒", "渣土车滴漏", "装修垃圾露天堆放", "消纳场违规倾倒"], verifiedScenes: ["工地周边", "城乡结合部", "消纳场卡口"], unsupported: ["不追踪车辆轨迹", "无法单凭图像认定责任主体"], boxes: [{ label: "建筑垃圾偷倒", confidence: "演示", x: 12, y: 49, width: 31, height: 26 }, { label: "渣土车抛洒", confidence: "演示", x: 51, y: 36, width: 34, height: 31 }], price: 2180, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-site", title: "工地施工违规识别", summary: "识别施工扬尘、裸土、围挡和出入口污染等违规线索。", slug: "urban-construction-site", problem: "从工地固定机位图像中发现施工环境违规线索。", category: "城市治理", scene: "urban-site", classes: ["可见施工扬尘", "裸土未覆盖", "围挡超范围", "围挡破损", "施工机械违规作业", "黄土裸露", "工地出入口污染"], verifiedScenes: ["房建工地", "道路工地", "工地出入口"], unsupported: ["扬尘受天气影响", "不判断施工许可"], boxes: [{ label: "可见施工扬尘", confidence: "演示", x: 42, y: 9, width: 37, height: 35 }, { label: "围挡破损", confidence: "演示", x: 67, y: 48, width: 22, height: 27 }], price: 2280, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-advertising", title: "户外广告与招牌识别", summary: "识别广告牌破损倾斜、广告布脱落和招牌掉落风险。", slug: "urban-advertising-signage", problem: "从街景图像中发现户外广告和店招的外观异常。", category: "城市治理", scene: "urban-advertising", classes: ["广告牌破损", "广告牌倾斜", "广告布脱落", "违规悬挂横幅", "店招破损", "店招掉落风险"], verifiedScenes: ["商业街区", "主次干道", "楼宇外立面"], unsupported: ["不判断广告内容合规性", "不替代结构安全鉴定"], boxes: [{ label: "广告牌倾斜", confidence: "演示", x: 9, y: 15, width: 27, height: 31 }, { label: "广告布脱落", confidence: "演示", x: 56, y: 12, width: 33, height: 27 }], price: 1980, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-municipal", title: "市政设施损坏识别", summary: "发现道路破损、井盖异常、路灯和城市家具损坏。", slug: "urban-municipal-damage", problem: "从市政巡查图像中识别道路和公共设施外观损坏。", category: "城市治理", scene: "urban-municipal", classes: ["道路坑槽", "道路破损", "井盖缺失", "井盖移位", "井盖破损", "路灯损坏", "路灯倾斜", "交通护栏损坏", "交通护栏缺失", "座椅破损", "垃圾桶破损"], verifiedScenes: ["城市道路", "人行道", "公园与广场"], unsupported: ["积水遮挡井盖", "不估算维修费用"], boxes: [{ label: "井盖缺失", confidence: "演示", x: 24, y: 58, width: 18, height: 16 }, { label: "路灯倾斜", confidence: "演示", x: 68, y: 7, width: 14, height: 63 }], price: 2180, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-water", title: "河道与水域污染识别", summary: "识别漂浮物、油污、禁钓禁泳行为和可见污水直排。", slug: "urban-water-pollution", problem: "从河道和水域巡查图像中发现污染和违规行为线索。", category: "城市治理", scene: "urban-water", classes: ["垃圾漂浮物", "水草漂浮物", "水面油污", "水面彩色污染", "禁钓区垂钓", "禁泳区游泳", "污水直排", "污水偷排"], verifiedScenes: ["城市河道", "湖泊闸口", "排污口巡查"], unsupported: ["不判断污染物成分", "水面强反光"], boxes: [{ label: "垃圾漂浮物", confidence: "演示", x: 16, y: 55, width: 23, height: 16 }, { label: "禁钓区垂钓", confidence: "演示", x: 72, y: 10, width: 15, height: 33 }], price: 2080, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-ecology", title: "生态环境问题识别", summary: "识别焚烧烟雾、工地扬尘和裸露地块扬尘。", slug: "urban-ecology-issues", problem: "从生态环境巡查图像中发现烟雾和扬尘视觉线索。", category: "城市治理", scene: "urban-ecology", classes: ["秸秆焚烧烟雾", "垃圾焚烧烟雾", "工地扬尘", "裸露地块扬尘"], verifiedScenes: ["城乡结合部", "农田与裸地", "工地周边"], unsupported: ["雾霾和云雾干扰", "不判断排放浓度"], boxes: [{ label: "秸秆焚烧烟雾", confidence: "演示", x: 18, y: 20, width: 30, height: 34 }, { label: "工地扬尘", confidence: "演示", x: 58, y: 40, width: 30, height: 27 }], price: 1880, quota: 16000 }),
  createMockAlgorithm({ id: "mock-alg-urban-fire", title: "火情与安全隐患识别", summary: "识别明火、浓烟、火灾蔓延迹象和易燃物违规堆放。", slug: "urban-fire-hazards", problem: "从城市监控图像中发现火情和安全隐患视觉线索。", category: "城市治理", scene: "urban-fire", classes: ["明火", "浓烟", "火灾蔓延迹象", "易燃物违规堆放"], verifiedScenes: ["社区与商铺", "工地与仓储", "室内外监控"], unsupported: ["不替代消防报警器", "强光反射干扰"], boxes: [{ label: "明火", confidence: "演示", x: 48, y: 47, width: 18, height: 27 }, { label: "浓烟", confidence: "演示", x: 37, y: 10, width: 36, height: 40 }], price: 2080, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-crowd", title: "人员聚集与公共安全识别", summary: "识别异常聚集、拥堵、突发事件现场和人流密度异常。", slug: "urban-crowd-safety", problem: "从公共空间监控图像中发现人群密度和秩序异常线索。", category: "城市治理", scene: "urban-crowd", classes: ["人员异常聚集", "人群拥堵", "突发事件现场", "人流密度异常"], verifiedScenes: ["商圈广场", "车站出入口", "大型活动场地"], unsupported: ["不识别个人身份", "密度阈值需按场所配置"], boxes: [{ label: "人员异常聚集", confidence: "演示", x: 30, y: 35, width: 40, height: 35 }, { label: "人群拥堵", confidence: "演示", x: 58, y: 57, width: 31, height: 27 }], price: 2280, quota: 18000 }),
  createMockAlgorithm({ id: "mock-alg-urban-traffic", title: "交通与停车秩序识别", summary: "识别禁停区违法停车、应急车道占用和无警示占道施工。", slug: "urban-traffic-order", problem: "从道路监控图像中发现停车和施工秩序异常线索。", category: "城市治理", scene: "urban-traffic", classes: ["禁停区违法停车", "应急车道占用", "交通拥堵", "占道施工无警示"], verifiedScenes: ["城市道路", "高速应急车道", "施工路段"], unsupported: ["不输出处罚结论", "需结合道路规则配置"], boxes: [{ label: "禁停区违法停车", confidence: "演示", x: 12, y: 55, width: 30, height: 22 }, { label: "占道施工无警示", confidence: "演示", x: 65, y: 18, width: 24, height: 28 }], price: 2180, quota: 20000 }),
  createMockAlgorithm({ id: "mock-alg-urban-greening", title: "园林绿化问题识别", summary: "识别毁绿种菜、树木倒伏折断、绿化带垃圾和黄土裸露。", slug: "urban-greening-issues", problem: "从公园和道路绿化巡查图像中发现绿化养护异常。", category: "城市治理", scene: "urban-greening", classes: ["毁绿种菜", "树木倒伏", "树木折断", "绿化带垃圾堆积", "绿地黄土裸露"], verifiedScenes: ["城市公园", "道路绿化带", "社区绿地"], unsupported: ["季节性养护混淆", "不评估树木健康等级"], boxes: [{ label: "毁绿种菜", confidence: "演示", x: 14, y: 54, width: 28, height: 22 }, { label: "树木倒伏", confidence: "演示", x: 51, y: 40, width: 35, height: 19 }], price: 1880, quota: 16000 }),
];

export const MOCK_ALGORITHM_LISTINGS: AlgorithmCatalogItem[] = [
  ...CORE_MOCK_ALGORITHM_LISTINGS,
  ...ROAD_ALGORITHM_LISTINGS,
  ...URBAN_ALGORITHM_LISTINGS,
];

function qualityReport(
  id: string,
  assetCount: number,
  classes: string[],
  coverage: number,
  advisories: string[],
): DatasetVersionQualityReport {
  const valid = Math.round(assetCount * 0.15);
  const test = Math.round(assetCount * 0.1);
  const train = assetCount - valid - test;
  return {
    dataset_version_id: id,
    schema_version: "1.0",
    asset_count: assetCount,
    split_counts: { train, valid, test },
    annotated_asset_count: Math.round(assetCount * coverage / 100),
    unannotated_asset_count: assetCount - Math.round(assetCount * coverage / 100),
    annotation_coverage_percent: coverage,
    class_distribution: classes.map((className, index) => ({
      class_id: index,
      class_name: className,
      annotation_count: Math.max(120, Math.round(assetCount * (1.25 - index * 0.12))),
      asset_count: Math.max(90, Math.round(assetCount * (0.72 - index * 0.07))),
    })),
    image_dimensions: {
      known_asset_count: assetCount,
      unknown_asset_count: 0,
      min_width: 640,
      max_width: 3840,
      min_height: 480,
      max_height: 2160,
    },
    advisories,
  };
}

const dataDefaults = {
  ...mockProvider,
  project_name: "SenseMu 数据精选",
  review_basis: "provider_attestation" as const,
  status: "published" as const,
  delivery_mode: "workspace_copy_after_authorization" as const,
  delivery_status: "prepared_not_open" as const,
  delivery_spec_hash: null,
  published_at: "2026-08-01T08:00:00Z",
  allow_derivative_models: true,
  allow_redistribution: false,
  contains_personal_data: false,
  privacy_treatment: "不包含可识别个人身份的信息；人像已做脱敏或只用于目标框标注。",
  custom_license_terms: null,
};

const dataSceneCategories: Record<CatalogScene, string> = {
  ppe: "安全生产",
  fire: "安全生产",
  traffic: "智慧交通",
  defect: "工业质检",
  parcel: "仓储物流",
  shelf: "智慧零售",
  forest: "林业",
  crop: "农业",
  orchard: "农业",
  apiary: "农业",
  "road-surface": "道路工程",
  "road-safety": "道路工程",
  "road-slope": "道路工程",
  "road-environment": "道路工程",
  tunnel: "道路工程",
  bridge: "道路工程",
  "urban-illegal": "城市治理",
  "urban-sanitation": "城市治理",
  "urban-construction-waste": "城市治理",
  "urban-site": "城市治理",
  "urban-advertising": "城市治理",
  "urban-municipal": "城市治理",
  "urban-water": "城市治理",
  "urban-ecology": "城市治理",
  "urban-fire": "城市治理",
  "urban-crowd": "城市治理",
  "urban-traffic": "城市治理",
  "urban-greening": "城市治理",
};

function dataListing(input: {
  id: string;
  scene: CatalogScene;
  title: string;
  summary: string;
  taskType: string;
  assetCount: number;
  classes: string[];
  source: string;
  method: string;
  coverage: string;
  limitations: string;
  license: DataMarketListing["license_code"];
  commercial: boolean;
  price: string;
  annotationType: string;
  imageSize: string;
  imageUrl?: string;
  aspectRatio?: number;
  boxes: PreviewBox[];
  coveragePercent: number;
  advisories: string[];
}): DataCatalogItem {
  const versionId = `${input.id}-v2`;
  return {
    ...dataDefaults,
    id: input.id,
    dataset_version_id: versionId,
    dataset_id: `${input.id}-dataset`,
    dataset_name: input.title,
    dataset_version_number: 2,
    task_type: input.taskType,
    asset_count: input.assetCount,
    class_map: Object.fromEntries(input.classes.map((name, index) => [String(index), name])),
    quality_report: qualityReport(versionId, input.assetCount, input.classes, input.coveragePercent, input.advisories),
    title: input.title,
    summary: input.summary,
    source_summary: input.source,
    collection_method: input.method,
    coverage_summary: input.coverage,
    known_limitations: input.limitations,
    license_code: input.license,
    allow_commercial_use: input.commercial,
    allow_model_training: true,
    preview: {
      scene: input.scene,
      alt: `${input.title}标注样例`,
      image_url: input.imageUrl,
      aspect_ratio: input.aspectRatio,
      boxes: input.boxes,
    },
    scene_category: dataSceneCategories[input.scene],
    price_label: input.price,
    annotation_type: input.annotationType,
    image_size_summary: input.imageSize,
    updated_label: "2026-07",
    is_mock: true,
  };
}

export const MOCK_DATA_LISTINGS: DataCatalogItem[] = [
  dataListing({
    id: "mock-data-ppe",
    scene: "ppe",
    title: "工地安全穿戴数据集",
    summary: "覆盖安全帽、反光衣和人员目标，适合训练工地安全检测模型。",
    taskType: "object-detection",
    assetCount: 18420,
    classes: ["人员", "安全帽", "未戴安全帽", "反光衣", "未穿反光衣"],
    source: "华东与华南 12 个真实工地的固定监控画面，经项目方授权整理。",
    method: "按工地、天气与时段分层抽样；两轮人工框选并交叉复核。",
    coverage: "包含室内外、晴雨天、日间与傍晚，以及 1–20 人不同密度。",
    limitations: "夜间无补光与极远距离人员样本较少；不建议直接用于人脸识别。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥6,800 / 版本",
    annotationType: "目标框",
    imageSize: "640p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[0].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.2,
    advisories: ["夜间样本占比 8.4%，部署到夜间场景前建议补充采样。"],
  }),
  dataListing({
    id: "mock-data-fire",
    scene: "fire",
    title: "仓储烟火异常数据集",
    summary: "烟雾、明火与正常蒸汽对照数据，用于仓储风险识别。",
    taskType: "object-detection",
    assetCount: 8630,
    classes: ["烟雾", "明火", "蒸汽"],
    source: "模拟实验、授权仓储监控与公开消防演练素材混合构成。",
    method: "以事件为单位切帧并去重，按事件来源隔离训练与测试划分。",
    coverage: "覆盖低照度、远距离、小火点、浅色烟雾与蒸汽干扰。",
    limitations: "户外森林火灾比例低；不包含红外热成像。",
    license: "CC-BY-4.0",
    commercial: true,
    price: "¥4,200 / 版本",
    annotationType: "目标框",
    imageSize: "720p–1080p",
    boxes: MOCK_ALGORITHM_LISTINGS[1].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 98.7,
    advisories: ["蒸汽对照样本集中于室内环境。"],
  }),
  dataListing({
    id: "mock-data-traffic",
    scene: "traffic",
    title: "城市路口车辆数据集",
    summary: "多城市固定高位相机采集的车辆检测与分类数据。",
    taskType: "object-detection",
    assetCount: 32680,
    classes: ["小客车", "货车", "公交车", "摩托车", "自行车"],
    source: "6 座城市、24 个路口的授权交通视频抽帧。",
    method: "按相机点位隔离划分，剔除连续重复帧后完成人工框选。",
    coverage: "覆盖晴雨、白天、夜间路灯与轻中度拥堵。",
    limitations: "极端暴雨和严重拥堵样本不足；车牌已模糊处理。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥9,600 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[2].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.6,
    advisories: ["夜间摩托车样本量低于其他类别。"],
  }),
  dataListing({
    id: "mock-data-defect",
    scene: "defect",
    title: "金属表面缺陷数据集",
    summary: "钢板与铝板表面的划痕、凹坑和氧化区域精细标注。",
    taskType: "segmentation",
    assetCount: 12940,
    classes: ["划痕", "凹坑", "氧化"],
    source: "3 条真实质检线与标准缺陷样片采集。",
    method: "固定光源与相机参数采集，使用像素级多边形标注并抽检。",
    coverage: "覆盖拉丝、磨砂和哑光材质，以及轻微到明显缺陷。",
    limitations: "不覆盖高反射镜面金属；跨产线使用前需验证光源差异。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥12,800 / 版本",
    annotationType: "多边形分割",
    imageSize: "2048 × 2048",
    boxes: MOCK_ALGORITHM_LISTINGS[3].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 100,
    advisories: ["凹坑类别占比为 12.6%，存在轻度不均衡。"],
  }),
  dataListing({
    id: "mock-data-parcel",
    scene: "parcel",
    title: "物流包裹传送带数据集",
    summary: "纸箱、软包和编织袋在分拣线上的检测标注数据。",
    taskType: "object-detection",
    assetCount: 22160,
    classes: ["纸箱", "软包", "编织袋"],
    source: "8 条快递分拣线的授权视频抽帧。",
    method: "按班次和相机点位去重，遮挡超过 70% 的目标不标注。",
    coverage: "覆盖不同传送带颜色、俯拍角度、包裹尺寸与堆叠程度。",
    limitations: "高速运动模糊样本偏少；不包含快递面单文字转录。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,200 / 版本",
    annotationType: "目标框",
    imageSize: "720p–2K",
    boxes: MOCK_ALGORITHM_LISTINGS[4].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 99.8,
    advisories: [],
  }),
  dataListing({
    id: "mock-data-shelf",
    scene: "shelf",
    title: "零售货架缺货数据集",
    summary: "商超货架空位、低库存与正常陈列的区域标注数据。",
    taskType: "object-detection",
    assetCount: 15780,
    classes: ["缺货区域", "低库存区域", "正常陈列"],
    source: "42 家便利店与商超的授权巡检图像。",
    method: "按门店隔离划分，区域框标注后由零售运营人员复核。",
    coverage: "覆盖饮料、粮油、零食与日化货架，以及不同照明和角度。",
    limitations: "冷柜反光与促销堆头样本较少；不包含 SKU 级商品识别。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥5,600 / 版本",
    annotationType: "区域框",
    imageSize: "1080p–4K",
    boxes: MOCK_ALGORITHM_LISTINGS[5].preview.boxes.map(({ label, x, y, width, height }) => ({ label, x, y, width, height })),
    coveragePercent: 98.9,
    advisories: ["正常陈列类别数量较多，训练时建议使用类别权重。"],
  }),
  dataListing({
    id: "mock-data-forest-health",
    scene: "forest",
    title: "林区树木健康数据集",
    summary: "林区航拍与固定机位图像，标注健康、枯死和倒伏树木。",
    taskType: "object-detection",
    assetCount: 14680,
    classes: ["健康树木", "疑似枯死树", "倒伏树木", "病害斑块"],
    source: "3 个林场的授权巡检航拍与林道监控图像。",
    method: "按林场与季节隔离划分，目标框标注后由林业巡检人员复核。",
    coverage: "覆盖针叶林、阔叶林、林缘与林道，以及晴天和阴天光照。",
    limitations: "浓雾和冬季落叶林样本较少；不用于树种级鉴定。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,400 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    imageUrl: "/catalog-forest.jpg",
    aspectRatio: 1600 / 1067,
    boxes: [
      { label: "疑似枯死树", x: 4, y: 20, width: 18, height: 63 },
      { label: "倒伏树木", x: 67, y: 54, width: 25, height: 18 },
    ],
    coveragePercent: 96.4,
    advisories: ["冬季落叶林样本占比 11.2%，跨季节部署前建议补充验证。"],
  }),
  dataListing({
    id: "mock-data-forest-fire",
    scene: "forest",
    title: "森林烟火监控数据集",
    summary: "林区烟雾、火点与云雾反光对照数据，用于早期火情识别。",
    taskType: "object-detection",
    assetCount: 9240,
    classes: ["烟雾", "火点", "云雾", "高亮反光"],
    source: "山地防火瞭望点与林区监控设备的授权视频抽帧。",
    method: "以事件为单位去重，按林区和天气隔离训练、验证与测试划分。",
    coverage: "覆盖远距离小烟柱、林缘火点、低云雾和日照反光干扰。",
    limitations: "夜间红外数据未包含在本版本；不覆盖地下火。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥5,900 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    imageUrl: "/catalog-forest.jpg",
    aspectRatio: 1600 / 1067,
    boxes: [{ label: "烟雾", x: 49, y: 4, width: 38, height: 30 }],
    coveragePercent: 98.1,
    advisories: ["云雾与烟雾对照样本已分层，但仍建议结合现场阈值复核。"],
  }),
  dataListing({
    id: "mock-data-produce",
    scene: "crop",
    title: "农产品分选数据集",
    summary: "蔬果品类与明显外观缺陷标注，适合收购与分选台训练。",
    taskType: "object-detection",
    assetCount: 32100,
    classes: ["苦瓜", "黄瓜", "胡萝卜", "辣椒", "疑似外观缺陷"],
    source: "4 个农产品收购点的分选台图像，经供应方授权整理。",
    method: "按收购点和日期隔离划分，密集堆叠目标由两名标注员交叉复核。",
    coverage: "覆盖不同品类、尺寸、成熟度和室内均匀光照。",
    limitations: "透明包装与严重堆叠样本较少；不包含重量估计标签。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,600 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    imageUrl: "/catalog-crop.jpg",
    aspectRatio: 1600 / 1067,
    boxes: [
      { label: "苦瓜", x: 8, y: 14, width: 41, height: 37 },
      { label: "黄瓜", x: 56, y: 8, width: 37, height: 43 },
      { label: "胡萝卜", x: 45, y: 48, width: 31, height: 39 },
    ],
    coveragePercent: 99.1,
    advisories: ["疑似外观缺陷类别已单独标注，适合先做人工复核再用于自动分选。"],
  }),
  dataListing({
    id: "mock-data-orchard",
    scene: "orchard",
    title: "果园果实计数数据集",
    summary: "果园行间与树冠近景的果实、未成熟果和病果标注数据。",
    taskType: "object-detection",
    assetCount: 24800,
    classes: ["果实", "未成熟果", "病果"],
    source: "5 个果园的授权采收前巡检图像。",
    method: "按果园和树行隔离划分，遮挡目标保留可见部分并记录复核状态。",
    coverage: "覆盖苹果、梨等树冠近景，以及不同成熟度和自然光照。",
    limitations: "强风运动模糊和完全遮挡果实样本偏少；不含产量真值。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,900 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    imageUrl: "/catalog-orchard.jpg",
    aspectRatio: 1600 / 1065,
    boxes: [
      { label: "果实", x: 43, y: 20, width: 12, height: 17 },
      { label: "果实", x: 58, y: 34, width: 14, height: 18 },
      { label: "病果", x: 22, y: 44, width: 13, height: 17 },
    ],
    coveragePercent: 97.8,
    advisories: ["病果类别占比 8.6%，训练时建议使用类别权重。"],
  }),
  dataListing({
    id: "mock-data-apiary",
    scene: "apiary",
    title: "蜂场巡检数据集",
    summary: "蜂箱、巡检人员与疑似空箱标注数据，适合蜂场资产盘点。",
    taskType: "object-detection",
    assetCount: 11760,
    classes: ["蜂箱", "巡检人员", "疑似空箱"],
    source: "2 个养蜂场的授权巡检与固定机位图像。",
    method: "按蜂场隔离划分，蜂箱区域框标注后由养蜂人员复核。",
    coverage: "覆盖蜂箱排列、植被背景、作业人员进入和白天自然光。",
    limitations: "蜂箱被高草完全遮挡和夜间样本较少；不替代人工蜂群健康判断。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥4,800 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–2K",
    imageUrl: "/catalog-apiary.jpg",
    aspectRatio: 1600 / 1063,
    boxes: [
      { label: "巡检人员", x: 16, y: 10, width: 38, height: 77 },
      { label: "蜂箱", x: 54, y: 23, width: 31, height: 49 },
    ],
    coveragePercent: 98.5,
    advisories: ["疑似空箱标签来自巡检记录，部署后建议与蜂场台账联动复核。"],
  }),
  dataListing({
    id: "mock-data-road-surface",
    scene: "road-surface",
    title: "路面病害识别数据集",
    summary: "覆盖裂缝、坑槽、车辙与沉陷等典型路面病害，服务道路巡检与养护优先级判断。",
    taskType: "object-detection",
    assetCount: 26840,
    classes: ["横向裂缝", "纵向裂缝", "网状裂缝", "坑槽", "车辙", "沉陷", "龟裂", "修补不良"],
    source: "国省干线与城市道路巡检车辆的授权图像，覆盖不同路龄和路面材质。",
    method: "按道路、方向和采集日期隔离划分，病害框选后由道路养护人员复核。",
    coverage: "覆盖沥青与水泥路面、晴天和阴天、近景与中远距离巡检视角。",
    limitations: "夜间、积雪和严重积水样本较少；裂缝宽度不代表结构安全等级。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥10,800 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "横向裂缝", x: 8, y: 40, width: 38, height: 9 },
      { label: "坑槽", x: 60, y: 52, width: 22, height: 18 },
      { label: "车辙", x: 31, y: 68, width: 28, height: 11 },
    ],
    coveragePercent: 98.3,
    advisories: ["网状裂缝与龟裂存在视觉相似，建议结合道路养护规范复核。"],
  }),
  dataListing({
    id: "mock-data-road-safety",
    scene: "road-safety",
    title: "交安设施识别数据集",
    summary: "识别护栏、防眩板、标志标牌、标线、轮廓标和防撞桶的缺失与损坏状态。",
    taskType: "object-detection",
    assetCount: 21460,
    classes: ["波形梁护栏缺失", "波形梁护栏损坏", "混凝土护栏污损", "护栏变形", "防眩板损坏", "防眩板缺失", "标志反光异常", "标牌倾斜", "标牌污损", "标线不清晰", "轮廓标", "防撞桶"],
    source: "高速公路与普通国省道巡检车图像，经运营单位授权采集。",
    method: "按路段隔离训练与测试，设施目标和状态标签由交安维护人员双人复核。",
    coverage: "覆盖中央分隔带、路侧、匝道和收费站前后，含白天与路灯夜景。",
    limitations: "强逆光和雨雪天气下反光效果标签需现场复核；不评估设施承载能力。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥9,400 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "护栏变形", x: 8, y: 47, width: 48, height: 18 },
      { label: "标牌倾斜", x: 67, y: 12, width: 18, height: 28 },
      { label: "防撞桶", x: 74, y: 66, width: 11, height: 20 },
    ],
    coveragePercent: 97.6,
    advisories: ["标志反光异常依赖采集角度，采购前建议核对现场验收标准。"],
  }),
  dataListing({
    id: "mock-data-road-slope",
    scene: "road-slope",
    title: "路基边坡异常数据集",
    summary: "覆盖滑坡、塌方、冲沟、防护网和挡墙异常，支持汛期巡检与风险排查。",
    taskType: "object-detection",
    assetCount: 12880,
    classes: ["滑坡", "塌方", "冲沟", "防护网破损", "挡墙开裂", "挡墙倾斜", "排水沟堵塞"],
    source: "山区公路巡检航拍、车载和固定点位图像，经管养单位授权整理。",
    method: "按山岭路段与季节隔离划分，异常区域框选后由地灾巡检人员复核。",
    coverage: "覆盖边坡、路堑、挡墙和排水设施，包含雨后与常态对照画面。",
    limitations: "极端灾害早期细微征兆样本有限；模型结果不能替代地质专业鉴定。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,900 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "滑坡", x: 42, y: 11, width: 42, height: 34 },
      { label: "防护网破损", x: 12, y: 38, width: 26, height: 27 },
      { label: "排水沟堵塞", x: 54, y: 72, width: 32, height: 13 },
    ],
    coveragePercent: 96.8,
    advisories: ["雨后样本占比 28.5%，旱季部署前建议补充常态样本。"],
  }),
  dataListing({
    id: "mock-data-road-environment",
    scene: "road-environment",
    title: "路域环境异常数据集",
    summary: "识别抛洒物、违法占用、绿化遮挡及烟雾、积水、结冰等异常路况。",
    taskType: "object-detection",
    assetCount: 19860,
    classes: ["散落物", "油污", "大件垃圾", "违章堆放", "占道施工", "枝叶侵入", "标志遮挡", "火灾烟雾", "积水", "结冰"],
    source: "城市道路与高速公路视频巡检抽帧，覆盖日常保洁和应急事件。",
    method: "按事件和路段去重，异常目标框选并由路政与养护人员交叉复核。",
    coverage: "覆盖主干路、匝道、服务区和施工区域，含晴雨天与不同交通密度。",
    limitations: "少见的大件抛洒物和结冰事件数量有限；不判断事故责任或处置时限。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,600 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [
      { label: "散落物", x: 28, y: 61, width: 17, height: 12 },
      { label: "占道施工", x: 57, y: 43, width: 31, height: 27 },
      { label: "枝叶侵入", x: 7, y: 7, width: 25, height: 34 },
    ],
    coveragePercent: 98,
    advisories: ["结冰样本较少，低温地区上线前应使用本地数据进行阈值校准。"],
  }),
  dataListing({
    id: "mock-data-tunnel",
    scene: "tunnel",
    title: "隧道设施异常数据集",
    summary: "覆盖洞口边坡、衬砌、排水和机电设施外观异常，适合隧道日常巡检。",
    taskType: "object-detection",
    assetCount: 10940,
    classes: ["洞口滑坡", "洞口落石", "防护网破损", "衬砌裂缝", "衬砌渗漏水", "衬砌剥落", "背后空洞迹象", "排水沟堵塞", "排水沟积水", "排水沟破损", "照明外观异常", "风机外观异常"],
    source: "公路隧道车载巡检与检修记录图像，经运营单位授权脱敏整理。",
    method: "按隧道和巡检批次隔离划分，设施异常框选后由隧道养护人员复核。",
    coverage: "覆盖洞口、拱顶、边墙、路面排水和照明风机，含进出洞光照变化。",
    limitations: "背后空洞仅标注可见迹象；不替代超声、雷达等无损检测手段。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,200 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "衬砌裂缝", x: 38, y: 21, width: 25, height: 12 },
      { label: "渗漏水", x: 67, y: 39, width: 15, height: 26 },
      { label: "照明外观异常", x: 10, y: 11, width: 16, height: 13 },
    ],
    coveragePercent: 97.1,
    advisories: ["隧道内低照度样本已覆盖，但严重积水和烟尘条件仍需现场复核。"],
  }),
  dataListing({
    id: "mock-data-bridge",
    scene: "bridge",
    title: "桥梁设施病害数据集",
    summary: "识别桥面、伸缩缝、支座、墩台与梁体病害，辅助桥梁巡检建档。",
    taskType: "object-detection",
    assetCount: 14260,
    classes: ["桥面裂缝", "桥面坑槽", "桥面车辙", "伸缩缝堵塞", "伸缩缝损坏", "伸缩缝错位", "支座老化", "支座开裂", "支座脱空", "支座偏位", "墩台冲刷", "混凝土剥落", "钢筋锈蚀", "梁体裂缝", "梁体渗水", "梁体白华"],
    source: "公路桥梁定期巡检、无人机和近距离检修图像，经管养单位授权。",
    method: "按桥梁与构件位置隔离划分，病害框选后由桥梁工程师抽检复核。",
    coverage: "覆盖桥面、伸缩缝、支座、墩台和梁体，含城市桥与跨河桥场景。",
    limitations: "支座脱空和内部锈蚀以外观迹象为主；不替代荷载试验与结构鉴定。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥9,800 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [
      { label: "桥面裂缝", x: 12, y: 47, width: 37, height: 10 },
      { label: "伸缩缝堵塞", x: 55, y: 51, width: 24, height: 14 },
      { label: "混凝土剥落", x: 74, y: 14, width: 15, height: 28 },
    ],
    coveragePercent: 97.9,
    advisories: ["支座类病害存在类别不均衡，训练时建议按构件分层抽样。"],
  }),
  dataListing({
    id: "mock-data-urban-illegal",
    scene: "urban-illegal",
    title: "违法建设识别数据集",
    summary: "识别楼顶新增搭建、露台封闭、阳光房和彩钢房等疑似违法建设变化。",
    taskType: "object-detection",
    assetCount: 15680,
    classes: ["楼顶新增搭建", "露台封闭", "阳光房", "彩钢房", "新建建筑", "外立面明显变化", "疑似违建脚手架", "疑似违建围挡"],
    source: "城市航拍、街景和网格巡查图像，经城管部门授权脱敏整理。",
    method: "按街道与采集日期隔离划分，变化区域框选后由规划执法人员抽检。",
    coverage: "覆盖老城区、城乡结合部、园区和住宅屋顶，包含多角度建筑外观。",
    limitations: "疑似标签不等同于执法认定；缺少完整历史影像时不判断新增时间。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,800 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "楼顶新增搭建", x: 48, y: 12, width: 28, height: 24 }, { label: "彩钢房", x: 14, y: 51, width: 27, height: 24 }, { label: "外立面明显变化", x: 70, y: 38, width: 19, height: 39 }],
    coveragePercent: 96.9,
    advisories: ["模型结果用于线索发现，正式认定需结合规划审批和现场核查。"],
  }),
  dataListing({
    id: "mock-data-urban-sanitation",
    scene: "urban-sanitation",
    title: "市容环境问题数据集",
    summary: "覆盖占道经营、游商小贩、垃圾堆积、乱贴乱画和非机动车乱停放。",
    taskType: "object-detection",
    assetCount: 22480,
    classes: ["占道摊位", "占道棚亭", "游商小贩", "垃圾堆积", "垃圾爆桶", "乱贴乱画", "违规广告", "非机动车乱停放", "店外经营", "店外乱堆放"],
    source: "城市道路、商圈和社区网格巡查图像，经采集单位授权。",
    method: "按街道和时段分层抽样，问题目标框选并由城管巡查员复核。",
    coverage: "覆盖主次干道、背街小巷、商圈和居民区，含早晚高峰与周末场景。",
    limitations: "不输出商户身份或处罚建议；夜间低照度和大型活动样本较少。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,900 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "占道摊位", x: 8, y: 48, width: 28, height: 28 }, { label: "垃圾爆桶", x: 65, y: 58, width: 18, height: 25 }, { label: "非机动车乱停放", x: 39, y: 70, width: 23, height: 16 }],
    coveragePercent: 98.2,
    advisories: ["垃圾堆积和正常临时摆放存在边界，建议结合区域规则复核。"],
  }),
  dataListing({
    id: "mock-data-urban-construction-waste",
    scene: "urban-construction-waste",
    title: "建筑垃圾与渣土数据集",
    summary: "识别建筑垃圾偷倒、渣土车抛洒滴漏、装修垃圾露天堆放和违规倾倒。",
    taskType: "object-detection",
    assetCount: 13760,
    classes: ["建筑垃圾偷倒", "建筑垃圾乱倒", "渣土车抛洒", "渣土车滴漏", "装修垃圾露天堆放", "消纳场违规倾倒"],
    source: "工地周边、道路卡口和消纳场的授权巡查视频抽帧。",
    method: "按事件去重并隔离同一车辆连续帧，异常区域由环卫与执法人员复核。",
    coverage: "覆盖工地出入口、城乡结合部、河道沿线和消纳场，含白天与夜间照明。",
    limitations: "不识别车牌或追踪车辆轨迹；偷倒行为需结合时间地点和运输台账核验。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥6,900 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "建筑垃圾偷倒", x: 12, y: 49, width: 31, height: 26 }, { label: "渣土车抛洒", x: 51, y: 36, width: 34, height: 31 }, { label: "装修垃圾露天堆放", x: 63, y: 68, width: 24, height: 18 }],
    coveragePercent: 97.3,
    advisories: ["夜间卡口样本占比 14.8%，部署前建议按摄像头补充夜间验证。"],
  }),
  dataListing({
    id: "mock-data-urban-site",
    scene: "urban-site",
    title: "工地施工违规数据集",
    summary: "覆盖施工扬尘、裸土未覆盖、围挡违规、机械违规作业和出入口污染。",
    taskType: "object-detection",
    assetCount: 17420,
    classes: ["可见施工扬尘", "裸土未覆盖", "围挡超范围", "围挡破损", "施工机械违规作业", "黄土裸露", "工地出入口污染"],
    source: "城市工地固定机位和巡查车辆图像，经建设单位授权整理。",
    method: "按工地隔离训练与测试，问题区域框选后由施工监管人员复核。",
    coverage: "覆盖房建、市政、道路和拆迁工地，含晴天、风天及出入口车辆通行。",
    limitations: "扬尘可见性受光照和风速影响；不判断施工许可和工程安全等级。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,400 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "可见施工扬尘", x: 42, y: 9, width: 37, height: 35 }, { label: "裸土未覆盖", x: 11, y: 60, width: 29, height: 20 }, { label: "围挡破损", x: 67, y: 48, width: 22, height: 27 }],
    coveragePercent: 97.8,
    advisories: ["扬尘与雾霾存在视觉混淆，建议联动气象数据进行告警复核。"],
  }),
  dataListing({
    id: "mock-data-urban-advertising",
    scene: "urban-advertising",
    title: "户外广告与招牌数据集",
    summary: "识别广告牌破损倾斜、广告布脱落、违规横幅和店招掉落风险。",
    taskType: "object-detection",
    assetCount: 11680,
    classes: ["广告牌破损", "广告牌倾斜", "广告布脱落", "违规悬挂横幅", "店招破损", "店招掉落风险"],
    source: "商业街区、主次干道和楼宇外立面巡查图像，经管理单位授权。",
    method: "按街区隔离划分，广告与招牌区域标注后由市容管理人员复核。",
    coverage: "覆盖楼顶、墙面、门头和道路横幅，包含近景巡查和远距离街景。",
    limitations: "不判断广告内容合规性和结构安全等级；夜间霓虹光照样本有限。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥5,800 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "广告牌倾斜", x: 9, y: 15, width: 27, height: 31 }, { label: "广告布脱落", x: 56, y: 12, width: 33, height: 27 }, { label: "店招破损", x: 39, y: 53, width: 31, height: 25 }],
    coveragePercent: 98.4,
    advisories: ["掉落风险为外观线索，需由专业单位进行结构复核。"],
  }),
  dataListing({
    id: "mock-data-urban-municipal",
    scene: "urban-municipal",
    title: "市政设施损坏数据集",
    summary: "覆盖道路破损、井盖缺失移位、路灯异常、护栏和城市家具损坏。",
    taskType: "object-detection",
    assetCount: 18940,
    classes: ["道路坑槽", "道路破损", "井盖缺失", "井盖移位", "井盖破损", "路灯损坏", "路灯倾斜", "交通护栏损坏", "交通护栏缺失", "座椅破损", "垃圾桶破损"],
    source: "城市道路、广场、公园和街区的网格巡查图像。",
    method: "按行政区和设施类型分层，设施异常框选后由市政维护人员复核。",
    coverage: "覆盖机动车道、非机动车道、人行道和公共空间，含日间与夜间路灯场景。",
    limitations: "不估算维修费用和安全等级；井盖遮挡或积水时可能漏检。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,100 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "井盖缺失", x: 24, y: 58, width: 18, height: 16 }, { label: "路灯倾斜", x: 68, y: 7, width: 14, height: 63 }, { label: "道路坑槽", x: 46, y: 71, width: 26, height: 14 }],
    coveragePercent: 98.6,
    advisories: ["井盖和道路破损类别已覆盖多种尺度，仍建议按本地设施规格补充验证。"],
  }),
  dataListing({
    id: "mock-data-urban-water",
    scene: "urban-water",
    title: "河道与水域污染数据集",
    summary: "识别河道漂浮物、水面油污、禁钓禁泳行为及可见污水直排。",
    taskType: "object-detection",
    assetCount: 12480,
    classes: ["垃圾漂浮物", "水草漂浮物", "水面油污", "水面彩色污染", "禁钓区垂钓", "禁泳区游泳", "污水直排", "污水偷排"],
    source: "河道、湖泊和排口固定机位及巡查船图像，经水务与生态部门授权。",
    method: "按水域和天气隔离划分，污染与行为目标由河道巡查人员复核。",
    coverage: "覆盖城市河道、湖泊、闸口和排污口，包含晴天、阴天及雨后水面。",
    limitations: "水面反光和藻类可能造成误报；不进行水质浓度和污染物成分判断。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥6,700 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "垃圾漂浮物", x: 16, y: 55, width: 23, height: 16 }, { label: "水面油污", x: 52, y: 39, width: 32, height: 18 }, { label: "禁钓区垂钓", x: 72, y: 10, width: 15, height: 33 }],
    coveragePercent: 96.7,
    advisories: ["污水直排属于可见线索，正式执法需结合排口检测和取样结果。"],
  }),
  dataListing({
    id: "mock-data-urban-ecology",
    scene: "urban-ecology",
    title: "生态环境问题数据集",
    summary: "覆盖秸秆与垃圾焚烧烟雾、工地扬尘和裸露地块扬尘等环境问题。",
    taskType: "object-detection",
    assetCount: 10260,
    classes: ["秸秆焚烧烟雾", "垃圾焚烧烟雾", "工地扬尘", "裸露地块扬尘"],
    source: "乡镇道路、农田、工地和生态巡查点位的授权图像与视频抽帧。",
    method: "按区域、季节和天气分层，烟雾及扬尘区域由环保巡查员复核。",
    coverage: "覆盖城乡结合部、农田、施工区域和裸地，含不同风向与背景植被。",
    limitations: "雾霾、云雾和蒸汽存在混淆；不判断排放浓度及污染责任主体。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥6,200 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "秸秆焚烧烟雾", x: 18, y: 20, width: 30, height: 34 }, { label: "工地扬尘", x: 58, y: 40, width: 30, height: 27 }, { label: "裸露地块扬尘", x: 39, y: 68, width: 28, height: 16 }],
    coveragePercent: 97.2,
    advisories: ["扬尘样本按天气分层，但高湿和逆光条件下仍需人工复核。"],
  }),
  dataListing({
    id: "mock-data-urban-fire",
    scene: "urban-fire",
    title: "火情与安全隐患数据集",
    summary: "识别明火、浓烟、火灾蔓延迹象和易燃物违规堆放等安全隐患。",
    taskType: "object-detection",
    assetCount: 13640,
    classes: ["明火", "浓烟", "火灾蔓延迹象", "易燃物违规堆放"],
    source: "社区、工地、仓储和沿街商铺的授权监控与巡查图像。",
    method: "以事件为单位去重，按场所隔离训练与测试并由消防人员复核。",
    coverage: "覆盖室内外、白天夜间、远近距离及烟雾遮挡等常见监控条件。",
    limitations: "不替代消防报警器和现场确认；小火点与强光反射可能混淆。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥6,500 / 版本",
    annotationType: "目标框",
    imageSize: "720p–4K",
    boxes: [{ label: "明火", x: 48, y: 47, width: 18, height: 27 }, { label: "浓烟", x: 37, y: 10, width: 36, height: 40 }, { label: "易燃物违规堆放", x: 70, y: 64, width: 20, height: 20 }],
    coveragePercent: 98.1,
    advisories: ["火灾蔓延迹象为视觉线索，告警策略需结合消防值守流程。"],
  }),
  dataListing({
    id: "mock-data-urban-crowd",
    scene: "urban-crowd",
    title: "人员聚集与公共安全数据集",
    summary: "识别人员异常聚集、拥堵、突发事件现场和大型活动人流密度异常。",
    taskType: "object-detection",
    assetCount: 14820,
    classes: ["人员异常聚集", "人群拥堵", "突发事件现场", "人流密度异常"],
    source: "商圈、广场、车站和大型活动的授权固定机位图像。",
    method: "按场所和活动隔离划分，人数区域与事件线索由安保人员复核。",
    coverage: "覆盖室内外公共空间、进出口和活动场地，含高峰与常态对照画面。",
    limitations: "不识别个人身份和情绪，不输出危险性判断；密度阈值需按场所配置。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥7,100 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "人员异常聚集", x: 30, y: 35, width: 40, height: 35 }, { label: "人群拥堵", x: 58, y: 57, width: 31, height: 27 }, { label: "突发事件现场", x: 9, y: 50, width: 18, height: 22 }],
    coveragePercent: 97.5,
    advisories: ["大型活动阈值应在现场容量和疏散方案基础上配置，不能直接套用样例。"],
  }),
  dataListing({
    id: "mock-data-urban-traffic",
    scene: "urban-traffic",
    title: "交通与停车秩序数据集",
    summary: "覆盖禁停区违法停车、应急车道占用、交通拥堵和占道施工未设警示。",
    taskType: "object-detection",
    assetCount: 20340,
    classes: ["禁停区违法停车", "应急车道占用", "交通拥堵", "占道施工无警示"],
    source: "城市道路、高速公路和施工路段的授权交通监控视频抽帧。",
    method: "按路段和时段隔离划分，车辆、拥堵区域和警示设施由交管人员复核。",
    coverage: "覆盖路口、主干道、匝道和应急车道，含早晚高峰、事故和施工场景。",
    limitations: "不输出车牌和处罚结论；拥堵判断需结合道路设计容量和实时流量。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥8,300 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "禁停区违法停车", x: 12, y: 55, width: 30, height: 22 }, { label: "应急车道占用", x: 55, y: 61, width: 28, height: 18 }, { label: "占道施工无警示", x: 65, y: 18, width: 24, height: 28 }],
    coveragePercent: 98.4,
    advisories: ["禁停区和应急车道标签需与道路电子地图及现场标线保持同步。"],
  }),
  dataListing({
    id: "mock-data-urban-greening",
    scene: "urban-greening",
    title: "园林绿化问题数据集",
    summary: "识别毁绿种菜、树木倒伏折断、绿化带垃圾和绿地黄土裸露。",
    taskType: "object-detection",
    assetCount: 13120,
    classes: ["毁绿种菜", "树木倒伏", "树木折断", "绿化带垃圾堆积", "绿地黄土裸露"],
    source: "城市公园、道路绿化带和社区绿地的网格巡查图像。",
    method: "按公园与街道隔离划分，异常区域由园林养护人员复核。",
    coverage: "覆盖行道树、花坛、草坪和社区绿地，包含春夏生长和雨后场景。",
    limitations: "季节性裸土和正常养护作业可能混淆；不评估树木健康和倒伏风险等级。",
    license: "CUSTOM-COMMERCIAL",
    commercial: true,
    price: "¥5,900 / 版本",
    annotationType: "目标框",
    imageSize: "1080p–4K",
    boxes: [{ label: "毁绿种菜", x: 14, y: 54, width: 28, height: 22 }, { label: "树木倒伏", x: 51, y: 40, width: 35, height: 19 }, { label: "绿地黄土裸露", x: 60, y: 68, width: 27, height: 15 }],
    coveragePercent: 98,
    advisories: ["季节性养护区域已做对照标注，仍建议与园林作业计划联动。"],
  }),
];

const previewFallbacks: CatalogPreview[] = MOCK_ALGORITHM_LISTINGS.map((item) => item.preview);

export function decorateAlgorithmListing(listing: MarketplaceListing, index = 0): AlgorithmCatalogItem {
  const preview = previewFallbacks[index % previewFallbacks.length];
  return {
    ...listing,
    is_mock: false,
    preview,
    metrics: [
      { label: "调用状态", value: "可用" },
      { label: "模型版本", value: `v${listing.model_version_number}` },
      { label: "月度额度", value: listing.monthly_quota_units.toLocaleString("zh-CN") },
    ],
    classes: [],
    model_architecture: listing.model_name,
    input_size: "按接口说明",
    latency_p95: "待供应商公布",
    evaluation_basis: "以供应商发布的验收材料为准",
    updated_label: listing.published_at ? listing.published_at.slice(0, 10) : "近期发布",
  };
}

export function decorateDataListing(listing: DataMarketListing, index = 0): DataCatalogItem {
  const preview = previewFallbacks[index % previewFallbacks.length];
  return {
    ...listing,
    is_mock: false,
    preview,
    scene_category: dataSceneCategories[preview.scene],
    price_label: "联系供应方",
    annotation_type: listing.task_type === "segmentation" ? "多边形分割" : "目标框",
    image_size_summary: listing.quality_report?.image_dimensions.max_width
      ? `最长边 ${listing.quality_report.image_dimensions.max_width}px`
      : "尺寸待确认",
    updated_label: listing.published_at.slice(0, 10),
  };
}

export function mergeAlgorithmListings(listings: MarketplaceListing[], includeMocks = false): AlgorithmCatalogItem[] {
  const real = listings.map(decorateAlgorithmListing);
  return includeMocks
    ? [...real, ...MOCK_ALGORITHM_LISTINGS.filter((mock) => !real.some((item) => item.title === mock.title))]
    : real;
}

export function mergeDataListings(listings: DataMarketListing[], includeMocks = false): DataCatalogItem[] {
  const real = listings.map(decorateDataListing);
  return includeMocks
    ? [...real, ...MOCK_DATA_LISTINGS.filter((mock) => !real.some((item) => item.title === mock.title))]
    : real;
}

export function findMockAlgorithm(id: string): AlgorithmCatalogItem | null {
  return MOCK_ALGORITHM_LISTINGS.find((item) => item.id === id) ?? null;
}

export function findMockData(id: string): DataCatalogItem | null {
  return MOCK_DATA_LISTINGS.find((item) => item.id === id) ?? null;
}
